SocialSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('registration.urls')),
	path('', include('account.urls')),
	path('', include('dialogs.urls')),
	path('', include('posts.urls')),
]

account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('account/', views.user_account, name = 'user_account'),
    path('account_setting/', views.account_setting, name = 'account_setting'),
    path('friends/', views.friends, name = 'friends'),
    path('friend_request/', views.friend_request, name = 'friend_request'),
    path('id<int:account_id>/add_friend', views.add_friend, name = 'add_friend'),
    path('id<int:account_id>/add_follower', views.add_follower, name = 'add_follower'),
    path('confirm_friend<int:account_id>/', views.confirm_friend, name = 'confirm_friend'),
    path('delete_friend<int:account_id>/', views.delete_friend, name = 'delete_friend'),
    path('delete_follower<int:account_id>/', views.delete_follower, name = 'delete_follower'),
    path('users/', views.find_users, name = 'find_users'),
    path('id<int:account_id>/', views.account, name = 'account'),
    ]

dialogs/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'dialogs'
urlpatterns = [
    path('dialog/<str:username>/', views.dialog, name = 'dialog'),
    path('dialog/<str:reciever_name>/leave_message/', views.leave_message, name = 'leave_message'),
    path('messages/', views.messages, name = 'messages'),
    path('post<str:username>/', views.post, name = 'post'),
    path('new_messages/', views.new_messages, name = 'new_messages'),
    path('message<int:message_id>/delete/', views.delete_message, name = 'delete_message'),
    path('dialog<int:companion_id>/delete/', views.delete_dialog, name = 'delete_dialog'),
    ]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('delete<int:post_id>/', views.delete_post, name = 'delete_post'),
    path('edit_post<int:post_id>/', views.edit_post, name = 'edit_post'),
    path('news/', views.news, name = 'news'),
    path('like_news/', views.like_news, name = 'like_news'),
    path('friend_news/', views.friend_news, name = 'friend_news'),
    path('news/like/', views.like_or_dislike, name = 'like_or_dislike'),
    path('news/user_like', views.user_like, name = 'user_like'),
    path('news<int:post_id>/leave_comment', views.leave_comment, name = 'leave_comment'),
    path('comment<int:comment_id>/delete', views.delete_comment, name = 'delete_comment'),
    path('news<int:post_id>/', views.post, name = 'post'),
    path('back/', views.back, name = 'back'),
]

registration/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'registration'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', standart_views.LoginView.as_view(), name='login'),
    path('logout/', standart_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.register, name = 'register'),
    ]

templates/base.html
<!doctype  html>
<html  lang="en">
<head>
  {% load static %}
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<link href="{% static 'css/base.css' %}" rel="stylesheet">
{% block style %}
{% endblock %}
<title>
  {% block title %}
  Проект регистрации
  {% endblock%}
</title>
</head>
<body>
  {% block main %}
  {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/menu.html
{% load static %}
  <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a href="{% url 'account:user_account' %}" class="btn btn-warning"><h3>DIARY</h3></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'account:user_account' %}" class="nav-link text-white ">Моя страница</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:friends' %}" class="nav-link text-white">Друзья <span class="badge badge-primary" id="new_friends"></span></a>
            </li>
            <li class="nav-item">
              <a href="{% url 'dialogs:messages' %}" class="nav-link text-white">Сообщения <span class="badge badge-primary" id="messages_count"></span></a>
            </li>
            <li class="nav-item">
              <a href="{% url 'posts:friend_news' %}" class="nav-link text-white">Новости</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'registration:logout' %}" class="nav-link text-danger">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'registration:login' %}" class="nav-link text-white">Войти</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'registration:register' %}" class="nav-link text-white">Зарегистрироваться</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="{% static 'js/dialogs/new_messages.js' %}" charset="utf-8"></script>
  <script type="text/javascript">
    var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // Для этих методов токен не будет подставляться в заголовок.
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
  </script>